services:
  app:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - LOKI_URL=http://loki:3100
      - JAEGER_URL=http://jaeger:4317
    volumes:
      - ./gateway/routes/docker.json:/app/routes/routes.json
    depends_on:
      - redis
      - loki
      - jaeger

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 8082:3002
    environment:
      - JAEGER_URL=http://jaeger:4317

  users:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 8083:3001
    environment:
      - JAEGER_URL=http://jaeger:4317

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./conf/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus
      - loki
      - jaeger

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-local-config.yaml
    volumes:
      - ./conf/loki-config.yaml:/etc/loki/loki-local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

networks:
  default:
    name: app

volumes:
  grafana-data:
  prometheus-data:
