{
 "title": "API Gateway",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "description": "Incoming Requests per route & status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, route_name, status) (increase(requests_total[$__interval]))",
     "legendFormat": "{{ method }} {{ route_name }} {{ status }}"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "description": "Requests Duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(method, route_name, status, quantile) (requests_duration_ms)",
     "legendFormat": "{{ method }} {{ route_name }} {{ status }} (p{{quantile}})"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"api-gateway\"}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Active Requests",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(active_requests)", "legendFormat": "__auto" }
   ]
  }
 ]
}